version: 2
jobs:
  build:
    macos:
      xcode: "9.3"
    steps:
      - brew install gcc
      - brew install bazel
      - checkout
      - BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 CC=$PWD/g++-wrapper bazel build //...
      - ./bazel-bin/fib 25
